---
server_id: ## example server
  settings: ## server settings
    prefix: "." ## default if not set is "."
    server_channels: ## server channels that are to be used
      admin: "" ## should be the channelid in string format
      log: "" ## should be the channelid in string format
    webhooks:
      ## If you want logging to go to discord follow this https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
      log: ## "https://discordapp.com/api/webhooks/GET-YOUR-OWN-WEBHOOK"
    mentions: ## the response the bot gives when it is mention in various channels.
      ping: ## if the bot is pinged in a message
        - ""
      mention: ## bot was pinged with no message
        - ""
    permissions: ## only simple permissions for now. These only apply to some filtering rules and some command usage.
      group: ## user groups. Currently These are not implimented. The Blacklist will ignore specific users
        admin: ## default to server owner having this permission
          roles:
            - ""
          users:
            - ""
        mod: ## no default users for this. Needs to be user ID's. Using roleID's is planned eventually.
          roles:
            - ""
          users:
            - ""
        blacklist: ## users in this group are ignored.
         - ""

    clear_commands: true ## clear out commands after processing them
  channel_groups: ## each channel is in a group. one to many channels can be in a single group.
    - ## example channel
      use_global: false
      channel_ids:
        - ""
      use_global: false
      mentions: ## the response the bot gives when it is mention in various channels.
        ping: ## if the bot is pinged in a message
        mention: ## bot was pinged with no message
        - "Please ask a question or supply your log into this chat"
      commands:
        example:
          response:
            - "Hello, I am a support bot created by `parkervcp` designed to help solve simple problems."
          reaction:
            - ""
      keywords:
        example:
          response:
            - ""
          reaction:
            - ""
      kick_on_mention:
        roles:
          - "" ## group ID's
        users:
          - "" ## group ID's
        message: ## message to send when kicking a user.
          - "Fire in the hole."
        reason:
          - "We don't support the <#linux-help> channel" ## DM the user with why they were kicked.
      parsing:
        image:
          filetype:
            - "png"
            - "jpg"
        paste:
          -
            name: pastebin
            URL: "https://pastebin.com/"
            format: "&url&raw/&filename&"
          - 
            name: hastebin
            URL: "https://hastebin.com/"
            format: "&url&raw/&filename&"