command:
  "help":
    - "Please check the github page at <https://github.com/parkervcp/parkertron>"
    - "The default config is a good example of how to set commands up. Try `.help command`"
    - "My base chat parsing function is also available. Try `.help chat` for more info"
    - "You can use for more information"
    - 
  "help command":
    - ""
    - 
  "help chat": 
    - ""
    - 
  "example":
    - ""
    - 