discord:
  token: "This is only an example..." ## You need to create an app and get a token here - https://discordapp.com/developers/
  ## If you want logging to go to discord follow this https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  webhook: "https://discordapp.com/api/webhooks/GET-YOUR-OWN-WEBHOOK." 
  prefix: "."
  mention:
    response: ":doughnut:"
    empty: "Please ask a question or supply your log into this chat"
    wrong_channel: "Please use one of the supported channels"
  channels:
    filter: false ## This will make the bot only filter messages from certain channels
    listening: ## The list of thannels to filter
      - "317335672245452801"
      - 