discord:
  token: "This is only an example..." ## You need to create an app and get a token here - https://discordapp.com/developers/
  owner: "" ## This is the UserID of the primary user. (usually you)
  prefix: "."
  channels:
    filter: false ## This will make the bot only filter messages from certain channels
    listening: ## The list of thannels to filter
      - "317335672245452801"
      - 
  group: ## user groups. Currently These are not implimented.
    admin:
      - 
    mods:
      - 
    blacklist:
      - 