permissions:
  discord:
    group: ## user groups. Currently These are not implimented. The Blacklist will ignore specific users
      admin:
        - 
      mods:
        - 
      blacklist:
        -
  irc:
    group: ## user groups. Currently These are not implimented. The Blacklist will ignore specific users
      admin:
        - 
      mods:
        - 
      blacklist:
        -